---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgtm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lgtm
  template:
    metadata:
      labels:
        app: lgtm
    spec:
      containers:
        - name: lgtm
          image: grafana/otel-lgtm:latest
          ports:
            - containerPort: 3000  # Grafana UI
            - containerPort: 4317  # OTLP gRPC
            - containerPort: 4318  # OTLP HTTP
            - containerPort: 3100  # Loki
            - containerPort: 9090  # Prometheus
            - containerPort: 3200  # Tempo
            - containerPort: 4040  # Pyroscope
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/ready
          # NOTE: By default OpenShift does not allow writing the root directory.
          # Thats why the data dirs for grafana, prometheus and loki can not be
          # created and the pod never becomes ready.
          # See: https://github.com/grafana/docker-otel-lgtm/issues/132
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: tempo-data
              mountPath: /data/tempo
            - name: grafana-data
              mountPath: /data/grafana
            - name: loki-data
              mountPath: /data/loki
            - name: loki-storage
              mountPath: /loki
            - name: p8s-storage
              mountPath: /data/prometheus
            - name: pyroscope-storage
              mountPath: /data/pyroscope
          env:
            - name: GF_SERVER_DOMAIN
              value: "localhost"
            - name: GF_SERVER_ROOT_URL
              value: http://localhost/lgtm
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
      volumes:
        - name: tempo-data
          emptyDir: {}
        - name: loki-data
          emptyDir: {}
        - name: grafana-data
          emptyDir: {}
        - name: loki-storage
          emptyDir: {}
        - name: p8s-storage
          emptyDir: {}
        - name: pyroscope-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lgtm
spec:
  selector:
    app: lgtm
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: otel-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otel-http
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: loki
      protocol: TCP
      port: 3100
      targetPort: 3100
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: tempo
      protocol: TCP
      port: 3200
      targetPort: 3200
    - name: pyroscope
      protocol: TCP
      port: 4040
      targetPort: 4040
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lgtm
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /lgtm/$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /lgtm(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: lgtm
            port:
              number: 3000