---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  - endpoints
  - pods
  - pods/log
  - events
  - configmaps
  - secrets
  - namespaces
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alloy
subjects:
- kind: ServiceAccount
  name: alloy
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
data:
  config.alloy: |
    logging {
      level  = "info"
      format = "logfmt"
    }

    discovery.kubernetes "nodes" {
      role = "node"
    }

    discovery.kubernetes "pods" {
      role = "pod"
    }

    // Prometheus
    
    /*
    prometheus.scrape "kubelet" {
      targets = discovery.kubernetes.nodes.targets
      forward_to = [prometheus.remote_write.default.receiver]
      
      scrape_interval = "30s"
      metrics_path = "/metrics"
      scheme = "https"
      bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
      tls_config {
        ca_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        insecure_skip_verify = true
      }
    }

    prometheus.scrape "cadvisor" {
      targets = discovery.kubernetes.nodes.targets
      forward_to = [prometheus.remote_write.default.receiver]
      
      scrape_interval = "30s"
      metrics_path = "/metrics/cadvisor"
      scheme = "https"
      bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
      tls_config {
        ca_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        insecure_skip_verify = true
      }
    }
    */
    
    prometheus.scrape "kube_state_metrics" {
      targets = [{
        __address__ = "kube-state-metrics.kube-system.svc.cluster.local:8080",
      }]
      forward_to = [prometheus.remote_write.default.receiver]
      
      scrape_interval = "30s"
      metrics_path = "/metrics"
    }

    discovery.relabel "scrape_pods" {
      targets = discovery.kubernetes.pods.targets

      rule {
          source_labels = ["__meta_kubernetes_namespace"]
          regex = "kube-system|kube-public|kube-node-lease|local-path-storage|default|ingress-nginx|cert-manager|monitoring"
          action = "drop"
       }
      
      // Keep only pods with prometheus.io/scrape annotation = true
      rule {
        source_labels = ["__meta_kubernetes_pod_annotation_prometheus_io_scrape"]
        regex         = "true"
        action        = "keep"
      }

      // Add namespace as a label
      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        target_label  = "namespace"
        action        = "replace"
      }

      // Add pod name as a label
      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        target_label  = "pod"
        action        = "replace"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_label_app"]
        target_label  = "app"
        action        = "replace"
      }
      
      // If prometheus.io/port is set, use it as the scrape port
      rule {
        source_labels = ["__address__", "__meta_kubernetes_pod_annotation_prometheus_io_port"]
        regex         = "([^:]+)(?::\\d+)?;(\\d+)"
        replacement   = "$1:$2"
        target_label  = "__address__"
        action        = "replace"
      }

      // If prometheus.io/path is set, use it as the scrape path
      rule {
        source_labels = ["__meta_kubernetes_pod_annotation_prometheus_io_path"]
        regex         = "(.+)"
        target_label  = "__metrics_path__"
        action        = "replace"
      }
    }

    prometheus.scrape "pod_metrics" {
      targets    = discovery.relabel.scrape_pods.output
      forward_to = [prometheus.remote_write.default.receiver]
    }
    
    prometheus.remote_write "default" {
      endpoint {
        url = "http://lgtm.default.svc.cluster.local:9090/api/v1/write"
      }
      
      external_labels = {
        cluster = "kind-local",
        source = "alloy",
      }
    }
    
    //loki
    discovery.relabel "pod_logs" {
       targets = discovery.kubernetes.pods.targets
       
       rule {
          source_labels = ["__meta_kubernetes_namespace"]
          regex = "kube-system|kube-public|kube-node-lease|local-path-storage|default|ingress-nginx|cert-manager|monitoring"
          action = "drop"
       }
       
       rule {
         source_labels = ["__meta_kubernetes_namespace"]
         target_label  = "namespace"
       }
       
       rule {
        source_labels = ["__meta_kubernetes_pod_label_app"]
        target_label  = "app"
       }

       rule {
         source_labels = ["__meta_kubernetes_pod_name"]
         target_label  = "pod"
       }
       
       rule {
         source_labels = ["__meta_kubernetes_pod_container_name"]
         target_label  = "container"
       }
    }

    loki.source.kubernetes "pods" {
      targets    = discovery.relabel.pod_logs.output
      forward_to = [loki.write.loki.receiver]
    }
    
    loki.write "loki" {
      endpoint {
        url = "http://lgtm.default.svc.cluster.local:3100/loki/api/v1/push"
      }
      external_labels = {
        cluster = "kind-local-cluster",
        source = "alloy",
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
spec:
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      serviceAccountName: alloy
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: alloy
        image: grafana/alloy:v1.5.0
        args:
        - run
        - /etc/alloy/config.alloy
        - --server.http.listen-addr=0.0.0.0:12345
        - --cluster.enabled=false
        - --disable-reporting=true
        - --storage.path=/tmp/alloy
        ports:
        - containerPort: 12345
          name: http-metrics
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
        volumeMounts:
        - name: config
          mountPath: /etc/alloy
        - name: tmp
          mountPath: /tmp
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: etcmachineid
          mountPath: /etc/machine-id
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: alloy-config
      - name: tmp
        emptyDir: {}
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: etcmachineid
        hostPath:
          path: /etc/machine-id
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  name: alloy
spec:
  selector:
    app: alloy
  ports:
  - name: http-metrics
    port: 12345
    targetPort: 12345
